doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            AppUserEntities:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/Entity'
                prefix: 'App\User\Domain\Entity'
                alias: AppUserEntities

            AppUserValueObjects:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Domain/ValueObject'
                prefix: 'App\User\Domain\ValueObject'
                alias: AppUserValueObjects

            AppRole:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Role/Domain/Entity'
                prefix: 'App\Role\Domain\Entity'
                alias: AppRole

            AppCommonEntities:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Common/Domain/Entity'
                prefix: 'App\Common\Domain\Entity'
                alias: AppCommonEntities

            AppCommonValueObjects:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Common/Domain/ValueObject'
                prefix: 'App\Common\Domain\ValueObject'
                alias: AppCommonValueObjects

            AppCart:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Cart/Domain/Entity'
                prefix: 'App\Cart\Domain\Entity'
                alias: AppCart

            AppProduct:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Domain/Entity'
                prefix: 'App\Product\Domain\Entity'
                alias: AppProduct

            AppOrder:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Order/Domain/Entity'
                prefix: 'App\Order\Domain\Entity'
                alias: AppOrder
        controller_resolver:
            auto_mapping: false

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
