framework:
    messenger:
        transports:
            product_changes_consumer:
                dsn: '%env(KAFKA_MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'product_changes'
                    kafka_conf:
                        group.id: '%kafka.global.group.id%'
                        enable.auto.offset.store: 'false'
                    topic_conf:
                        auto.offset.reset: 'earliest'

            notifications_producer:
                dsn: '%env(KAFKA_MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'notifications'

            reports_producer:
                dsn: '%env(KAFKA_MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    flushTimeout: 10000
                    flushRetries: 5
                    topic:
                        name: 'reports'

        routing:
            'App\Product\Domain\MessageBus\ProductChanges': product_changes_consumer
            'App\Common\Domain\MessageBus\Notification': notifications_producer
            'App\Order\Domain\MessageBus\Notification\Checkout\OrderCheckedOut': notifications_producer
            'App\Report\Domain\MessageBus\SoldProducts\SoldProductsReport': reports_producer
