framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.

when@test:
    framework:
        validation:
            not_compromised_password: false
