openapi: 3.1.0

info:
  title: Online Store
  description: Pet project. Developed by Nikitq
  version: 0.1.9

servers:
  - url: http://localhost/api
    description: Local

tags:
  - name: User

paths:
    /user/add:
      post:
        tags: [ User ]
        summary: Add a new user
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    minLength: 2
                    maxLength: 100
                    example: Иван Иванович
                    nullable: false
                  email:
                    type: string
                    minLength: 3
                    maxLength: 255
                    example: test@mail.ru
                    nullable: false
                  phone:
                    type: integer
                    size: 10
                    example: 8005553535
                    nullable: false
        responses:
          200:
            description: Has a user been added
            content:
              application/json:
                schema:
                  allOf:
                    - $ref: '#/components/schemas/SuccessfulResponseBodyScheme'
                    - type: object
                      properties:
                        data:
                          items:

          400:
            description: A request validation or business logic error has occurred
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/FailedResponseBodyScheme'
          500:
            description: An unexpected server error has occurred
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/FailedResponseBodyScheme'


components:
  schemas:
    SuccessfulResponseBodyScheme:
      type: object
      properties:
        status:
          description: Результат выполнения запроса
          type: string
          example: success
        data:
          description: Полезная нагрузка ответа
      required:
        - status
        - data
      additionalProperties: false

    FailedResponseBodyScheme:
      type: object
      properties:
        status:
          description: Результат выполнения запроса
          type: string
          example: error

        errors:
          description: Информация об ошибке при выполнении запроса
          type: array
          items:
            type: object
            properties:
              code:
                description: Код ошибки
                type: integer
                minimum: 1
              message:
                description: Описание ошибки
                type: string
              line:
                description: Строка ошибки
                type: string
              file:
                description: В каком файле ошибка
                type: string
              trace:
                description: Трассировка ошибки
                type: array
                items:
                  type: object
                  properties:
                    file:
                      type: string
                      minLength: 1
                    line:
                      type: integer
                      minimum: 1
                    function:
                      type: string
                      minLength: 1
                    class:
                      type: string
                    type:
                      type: string
                  required:
                    - file
                    - line
                    - function

            required:
              - code
            additionalProperties: false
      required:
        - status
        - error
      additionalProperties: false
