volumes:
  db-data:
  kafka-data:
  zookeeper-data:
  zookeeper-logs:

networks:
  online-store:
    driver: bridge

services:
  php-fpm:
    container_name: online-store_php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./../:/var/www/
    networks:
      - online-store
    ports:
      - "9000:9000"
      - "9003:9003"

  nginx:
    container_name: online-store_nginx
    build:
      context: ./nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./../:/var/www:rw
    depends_on:
      - php-fpm
    networks:
      - online-store

  db:
    image: postgres:latest
    container_name: online-store-db
    environment:
      DEBUG: ${APP_DEBUG:-false}
      POSTGRES_DB: ${POSTGRES_DB:-online-store}
      POSTGRES_USER: ${POSTGRES_USER:-online-store}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?error}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    networks:
      - online-store

  swagger:
    image: swaggerapi/swagger-ui
    container_name: online-store-swagger_ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /app/swagger.yaml
    volumes:
      - ./../swagger/api.yaml:/app/swagger.yaml
    networks:
      - online-store

  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    container_name: online-store_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
        # Kafka won't work without zookeeper volume data
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log

    networks:
      - online-store

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    container_name: online-store_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'online-store_zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INSIDE://online-store_kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka-data:/var/lib/kafka/data:rw
    networks:
      - online-store

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: online-store_kafka_ui
    depends_on:
      - kafka
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "online-store_kafka:9092"
      DYNAMIC_CONFIG_ENABLED: "true"
    networks:
      - online-store
